# Generated by Django 5.2 on 2025-04-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithm", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["id_num"],
                "verbose_name": "题目",
                "verbose_name_plural": "题目列表",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="id_num",
            field=models.PositiveIntegerField(
                default=1,
                editable=False,
                help_text="用于排序的数字部分",
                unique=True,
                verbose_name="数字ID",
            ),
            preserve_default=False,
        ),
    ]
