# Generated by Django 5.2 on 2025-05-02 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("algorithm", "0002_alter_question_options_question_id_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="solution",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="是否已删除"),
        ),
    ]
